"use client";
import {useMemo,useState} from "react";
import {Area,AreaChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {interesCompuesto} from "@/lib/calculators/finance";
const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"USD",maximumFractionDigits:0});
export default function CompoundInterestCalculator(){
 const [capital,setCapital]=useState(5000),[aporte,setAporte]=useState(600),[tasa,setTasa]=useState(9),[inflacion,setInflacion]=useState(3),[anios,setAnios]=useState(4);
 const r=useMemo(()=>interesCompuesto({capitalInicial:capital,aporteMensual:aporte,tasaAnual:tasa,inflacionAnual:inflacion,anios}),[capital,aporte,tasa,inflacion,anios]);
 const input=(label:string,v:number,set:(n:number)=>void,suf="")=><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">{label}</span><div className="flex rounded-xl border border-crema-200 bg-crema px-3"><input className="min-w-0 flex-1 bg-transparent py-3 outline-none tabular" type="number" inputMode="decimal" value={v} min="0" onFocus={e=>e.currentTarget.select()} onChange={e=>set(Math.max(0,Number(e.target.value)))}/>{suf&&<span className="self-center text-tinta/45">{suf}</span>}</div></label>;
 return <div className="space-y-8"><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-4 rounded-2xl border border-crema-200 bg-crema-50 p-6 sm:grid-cols-2">{input("Capital inicial",capital,setCapital,"USD")}{input("Aporte mensual",aporte,setAporte,"USD")}{input("Tasa anual",tasa,setTasa,"%")}{input("Inflación anual esperada",inflacion,setInflacion,"%")}{input("Plazo",anios,setAnios,"años")}</div><div className="rounded-2xl bg-oliva p-7 text-crema"><p className="text-xs font-bold uppercase tracking-wider text-crema/60">Capital final estimado</p><p className="mt-2 font-serif text-5xl tabular">{money.format(r.saldo)}</p><div className="mt-7 grid grid-cols-2 gap-4 border-t border-crema/20 pt-5 text-sm"><div><p className="text-crema/60">Aportes</p><b>{money.format(r.aportes)}</b></div><div><p className="text-crema/60">Rendimiento</p><b>{money.format(r.ganancia)}</b></div><div className="col-span-2"><p className="text-crema/60">Valor real de hoy*</p><b className="text-xl">{money.format(r.saldoReal)}</b></div></div></div></div><div className="h-72 rounded-2xl border border-crema-200 bg-crema-50 p-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={r.serie}><XAxis dataKey="mes" tickFormatter={v=>String(Math.round(Number(v)/12))+"a"}/><YAxis tickFormatter={v=>"$"+Intl.NumberFormat("es-AR",{notation:"compact"}).format(Number(v))}/><Tooltip formatter={v=>money.format(Number(v))}/><Area type="monotone" dataKey="saldo" stroke="var(--color-oliva)" fill="var(--color-oliva-100)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><p className="text-xs leading-relaxed text-tinta/55">*Valor real descontando la inflación anual ingresada. Simulación educativa: la rentabilidad y la inflación futuras no están garantizadas.</p></div>
}
