"use client";
import {useEffect,useMemo,useState} from "react"; import {Building2,Info} from "lucide-react"; import {useApi} from "@/lib/useApi"; import type {Indicadores,Punto} from "@/lib/types"; import {ajusteIPC,ajusteIndice,ajustePorcentaje,type RentIndex} from "@/lib/calculators/rent"; import {mesesDisponibles} from "@/lib/calculators/inflation";
const ars=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
const meses=["ene","feb","mar","abr","may","jun","jul","ago","sep","oct","nov","dic"]; function em(s:string){const [y,m]=s.split("-").map(Number);return `${meses[m-1]} ${y}`}
function cercano(serie:Punto[],fecha:string,modo:"inicio"|"fin"){const xs=serie.filter(p=>modo==="inicio"?p.fecha>=fecha:p.fecha<=fecha);return modo==="inicio"?xs[0]:xs.at(-1)}
export default function RentCalculator(){
 const {data,loading}=useApi<Indicadores>("/api/indicadores",3600000); const ms=useMemo(()=>mesesDisponibles(data?.inflacionSerie??[]),[data]);
 const [monto,setMonto]=useState(500000),[indice,setIndice]=useState<RentIndex>("ipc"),[desdeE,setDesde]=useState(""),[hastaE,setHasta]=useState(""),[pct,setPct]=useState(15),[fechaI,setFechaI]=useState("2025-10-01"),[fechaF,setFechaF]=useState(new Date().toISOString().slice(0,10)),[icl,setIcl]=useState<Punto[]>([]),[iclLoad,setIclLoad]=useState(false);
 const desde=desdeE||ms.at(-4)||ms[0]||"", hasta=hastaE||ms.at(-1)||"";
 useEffect(()=>{if(indice!=="icl"||!fechaI||!fechaF||fechaI>fechaF)return;setIclLoad(true);fetch(`/api/icl?desde=${fechaI}&hasta=${fechaF}`).then(r=>r.json()).then(j=>setIcl(j.serie??j.data?.serie??[])).catch(()=>setIcl([])).finally(()=>setIclLoad(false))},[indice,fechaI,fechaF]);
 const ii=cercano(icl,fechaI,"inicio"),iff=cercano(icl,fechaF,"fin");
 const r=indice==="ipc"?ajusteIPC(monto,desde,hasta,data?.inflacionSerie??[]):indice==="icl"&&ii&&iff?ajusteIndice(monto,ii.valor,iff.valor):indice==="porcentaje"?ajustePorcentaje(monto,pct):null;
 if(loading&&!data)return <div className="rounded-2xl border border-crema-200 p-8">Cargando datos…</div>;
 return <div className="space-y-8"><div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><div className="space-y-5 rounded-2xl border border-crema-200 bg-crema-50 p-6"><div className="flex items-center gap-3"><span className="rounded-xl bg-oliva-100 p-2.5 text-oliva"><Building2 size={22}/></span><b>Datos del alquiler</b></div><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Alquiler a actualizar</span><input className="calc-number w-full rounded-xl border border-crema-200 bg-crema p-3" type="number" inputMode="decimal" min="1" value={monto} onFocus={e=>e.currentTarget.select()} onChange={e=>setMonto(Math.max(0,Number(e.target.value)))}/></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Mecanismo</span><select className="w-full rounded-xl border border-crema-200 bg-crema p-3" value={indice} onChange={e=>setIndice(e.target.value as RentIndex)}><option value="ipc">IPC acumulado</option><option value="icl">ICL · BCRA</option><option value="porcentaje">Porcentaje pactado</option></select></label>
 {indice==="ipc"?<div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Desde</span><select className="w-full rounded-xl border border-crema-200 bg-crema p-3" value={desde} onChange={e=>setDesde(e.target.value)}>{ms.map(m=><option key={m} value={m}>{em(m)}</option>)}</select></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Hasta</span><select className="w-full rounded-xl border border-crema-200 bg-crema p-3" value={hasta} onChange={e=>setHasta(e.target.value)}>{ms.filter(m=>m>=desde).map(m=><option key={m} value={m}>{em(m)}</option>)}</select></label></div>:indice==="icl"?<div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Fecha inicial</span><input className="w-full rounded-xl border border-crema-200 bg-crema p-3" type="date" min="2020-06-30" value={fechaI} onChange={e=>setFechaI(e.target.value)}/></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Fecha de ajuste</span><input className="w-full rounded-xl border border-crema-200 bg-crema p-3" type="date" value={fechaF} onChange={e=>setFechaF(e.target.value)}/></label>{ii&&iff&&<p className="col-span-full text-xs text-tinta/55">ICL inicial: {ii.valor.toFixed(4)} ({ii.fecha}) · ICL final: {iff.valor.toFixed(4)} ({iff.fecha})</p>}</div>:<label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">Aumento pactado</span><div className="flex rounded-xl border border-crema-200 bg-crema px-3"><input className="calc-number flex-1 bg-transparent py-3 outline-none" type="number" inputMode="decimal" min="0" value={pct} onFocus={e=>e.currentTarget.select()} onChange={e=>setPct(Math.max(0,Number(e.target.value)))}/><span className="self-center">%</span></div></label>}</div>
 <div className="rounded-2xl bg-oliva p-7 text-crema"><p className="text-xs font-bold uppercase tracking-wider text-crema/60">Nuevo alquiler estimado</p><p className="mt-3 font-serif text-5xl">{iclLoad?"…":r?ars.format(r.montoNuevo):"—"}</p>{r&&<><p className="mt-5 text-sm text-crema/65">Ajuste acumulado</p><p className="text-2xl font-bold">{r.aumento.toFixed(2)}%</p><p className="mt-6 border-t border-crema/20 pt-5 text-sm text-crema/70">Diferencia mensual: <b className="text-crema">{ars.format(r.montoNuevo-monto)}</b></p></>}</div></div>
 <div className="rounded-2xl border border-crema-200 p-5 text-sm"><div className="mb-2 flex items-center gap-2 font-bold"><Info size={17}/> Fuente y criterio</div><p className="leading-relaxed text-tinta/65">{indice==="ipc"?"Se encadenan las variaciones mensuales del IPC; los porcentajes no se suman. Usa la misma serie de IPC de DL Mercado.":indice==="icl"?"ICL oficial del BCRA. El ajuste se obtiene como alquiler × (ICL de la fecha de actualización / ICL de la fecha inicial). Si la fecha no tiene observación, se usa la observación disponible dentro del rango consultado.":"Aplica directamente el porcentaje pactado ingresado por el usuario."}</p><p className="mt-3 text-xs text-tinta/50">Herramienta de cálculo. Verificá siempre el índice, las fechas y la periodicidad establecidos en tu contrato.</p></div></div>
}