"use client";
import {useMemo,useState} from "react"; import {retiro} from "@/lib/calculators/finance";
const usd=new Intl.NumberFormat("es-AR",{style:"currency",currency:"USD",maximumFractionDigits:0});
export default function RetirementCalculator(){
 const [edad,setEdad]=useState(33),[retiroEdad,setRetiroEdad]=useState(65),[capital,setCapital]=useState(5000),[aporte,setAporte]=useState(600),[tasa,setTasa]=useState(7),[inflacion,setInflacion]=useState(3),[objetivo,setObjetivo]=useState(500000);
 const r=useMemo(()=>retiro({edadActual:edad,edadRetiro:retiroEdad,capitalInicial:capital,aporteMensual:aporte,tasaAnual:tasa,inflacionAnual:inflacion,anios:retiroEdad-edad,capitalObjetivo:objetivo}),[edad,retiroEdad,capital,aporte,tasa,inflacion,objetivo]);
 const f=(l:string,v:number,s:(n:number)=>void,u="")=><label><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-tinta/60">{l}</span><div className="flex rounded-xl border border-crema-200 bg-crema px-3"><input className="min-w-0 flex-1 bg-transparent py-3 outline-none" type="number" min="0" value={v} onChange={e=>s(Math.max(0,Number(e.target.value)))}/><span className="self-center text-tinta/45">{u}</span></div></label>;
 return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="grid gap-4 rounded-2xl border border-crema-200 bg-crema-50 p-6 sm:grid-cols-2">{f("Edad actual",edad,setEdad,"años")}{f("Edad de retiro",retiroEdad,setRetiroEdad,"años")}{f("Capital actual",capital,setCapital,"USD")}{f("Aporte mensual",aporte,setAporte,"USD")}{f("Rentabilidad anual",tasa,setTasa,"%")}{f("Inflación anual",inflacion,setInflacion,"%")}{f("Objetivo en dinero de hoy",objetivo,setObjetivo,"USD")}</div><div className="rounded-2xl bg-oliva p-7 text-crema"><p className="text-xs font-bold uppercase tracking-wider text-crema/60">Capital proyectado a los {retiroEdad}</p><p className="mt-2 font-serif text-5xl">{usd.format(r.saldo)}</p><p className="mt-6 text-sm text-crema/65">Equivalente en poder adquisitivo de hoy</p><p className="text-2xl font-bold">{usd.format(r.saldoReal)}</p><div className="mt-6 border-t border-crema/20 pt-5"><p className="text-sm text-crema/65">Avance hacia tu objetivo real</p><p className="mt-1 text-2xl font-bold">{Math.min(r.cumplimiento,999).toFixed(1)}%</p><div className="mt-3 h-2 overflow-hidden rounded bg-crema/20"><div className="h-full bg-crema" style={{width:`${Math.min(100,r.cumplimiento)}%`}}/></div>{r.brechaReal>0&&<p className="mt-3 text-sm">Brecha estimada: {usd.format(r.brechaReal)}</p>}</div></div></div><p className="text-xs leading-relaxed text-tinta/55">Simulación educativa y no asesoramiento financiero. Trabaja en USD y en términos reales para evitar que una cifra nominal de largo plazo distorsione la comparación.</p></div>
}
